version: '3.5'
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      BASE_URL: "https://acc.api.data.amsterdam.nl/"
    #volumes:
      #- "./src:/usr/share/nginx/html/"

  test:
    build:
      context: .
      target: build-deps
    environment:
      - NODE_ENV=test
